----SCRIPT SQL----

CREATE TABLE CAMPANAS_POLITICAS (
    ID NUMBER PRIMARY KEY,
    CANDIDATO VARCHAR2(150),
    PARTIDO_POLITICO VARCHAR2(150),
    EVENTO VARCHAR2(150),
    FECHA_EVENTO VARCHAR2(20),
    UBICACION VARCHAR2(150),
    ASISTENTES_ESTIMADOS NUMBER,
    CAMPANA_ACTIVA VARCHAR2(10)
);
----CONSULTAS----
SELECT * FROM CAMPANAS_POLITICAS;
TRUNCATE TABLE CAMPANAS_POLITICAS;
COMMIT;